spring.application.name=chatbot

spring.config.import=optional:file:C:/Users/divsutar/OneDrive/Desktop/navproject/IKS chatbot/chatbot/local.properties
spring.ai.vectorstore.chroma.client.host=${CLIENT_HOST}
spring.ai.vectorstore.chroma.client.port=8000
spring.ai.vectorstore.chroma.tenant-name=SpringAiTenant
spring.ai.vectorstore.chroma.database-name=SpringAiDatabase
spring.ai.vectorstore.chroma.collection-name=SpringAiCollection
spring.ai.vectorstore.chroma.initialize-schema=true

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=${GROQ_MODEL}
spring.ai.openai.chat.max-tokens=1000

spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.text.model=gemini-embedding-001

