spring.application.name=chatbot

spring.config.import=optional:file:local.properties
spring.ai.vectorstore.chroma.client.host=${CLIENT_HOST:http://localhost}
spring.ai.vectorstore.chroma.client.port=${CLIENT_PORT:8000}
spring.ai.vectorstore.chroma.tenant-name=${CHROMA_TENANT:default_tenant}
spring.ai.vectorstore.chroma.database-name=${CHROMA_DATABASE:default_database}
spring.ai.vectorstore.chroma.collection-name=SpringAiCollection
spring.ai.vectorstore.chroma.initialize-schema=true

spring.ai.openai.api-key=${GROQ_API_KEY:}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=${GROQ_MODEL:llama-3.3-70b-versatile}
spring.ai.openai.chat.max-tokens=1000

spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY:}
spring.ai.google.genai.embedding.text.model=gemini-embedding-001


